apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cv-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cv-service
    spec:
      containers:
      - name: cv-service
        image:  aardelean/cv-service:1.3
        ports:
        - name: cvs-port
          containerPort: 8220
        env:
        - name: FULL_TEXT_REPOSITORY_HOST
          value: search-repository-service
        - name: FULL_TEXT_REPOSITORY_PORT
          value: "8080"
        - name: PERSISTENCE_REPOSITORY_HOST
          value: persistence-repository-service
        - name: PERSISTENCE_REPOSITORY_PORT
          value: "8180"
        - name: example.property
          valueFrom:
            configMapKeyRef:
              name: example-config
              key:  example.property
---
apiVersion: v1
kind: Service
metadata:
  name: cv-service-service
  labels:
    app:  cv-backend
spec:
  ports:
  - port: 8220
    name: backend-port
    targetPort: cvs-port
    protocol: TCP
  selector:
    app:  cv-service
  type: NodePort
